name: Lint docs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  checks: write

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download styles
      run: |
        curl -s https://vale-library.netlify.app/styles.zip -o styles.zip
        unzip styles.zip -d .github/styles
        rm styles.zip

    - name: Vale
      uses: errata-ai/vale-action@v2
      with:
        files: '["src", "README.md"]'
        fail_on_error: true
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
